[book]
title = "Wrapsher"
authors = ["Mermaidpurse"]
description = "The Wrapsher programming language."
language = "en"
multilingual = false
src = "docs"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
smart-punctuation = true
git-repository-url = "https://github.com/mermaidpurse/wrapsher"
git-repository-icon = "fa-github"
additional-js = ["theme/wrapsher-hljs.js"]
additional-css = ["theme/css/sidebar.css", "theme/css/profont.css"]
favicon = "images/wrapsher-logo-64.png"

[output.html.search]
enable = true
limit-results = 20
teaser-word-count = 30

[output.html.print]
enable = true
